# See https://wiki.hyprland.org/Configuring/Monitors/
# List current monitors and resolutions possible: hyprctl monitors
# Format: monitor = [port], resolution, position, scale

# Default setup
env = GDK_SCALE,1
monitor=,preferred,auto,1

# Main laptop monitor
monitor = desc:BOE 0x091D,                  preferred, 1920x0, 1

# Actual monitors
monitor = desc:e-Net Inc S2-L S2-L 20240426, preferred, 0x0, 1
monitor = desc:DTR S2-R S2-R 20240426,     preferred, 3840x0, 1
